apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-service-app
  template:
    metadata:
      labels:
        app: hello-world-service-app
    spec:
      containers:
        - name: hello-world-service-app
          image: kotak/hello-world-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: hello-world-service
spec:
  selector:
    # Selector for Pods
    app: hello-world-service-app
  ports:
    # Port Map
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer